### ISSUE TITLE
Not working on Anki 2.1.50 Beta and RCs

### ISSUE THREAD

**Issue by cjdduarte** [FooSoft/anki-connect#308]
Not working on Anki 2.1.50 Beta and RCs

I used the standard example example to create deck

invoke('createDeck', deck='test1')
result = invoke('deckNames')
print('got list of decks: {}'.format(result))

Works on 2.1.49. But in this new version 2.1.50 (beta 6) no.

**Comment by cjdduarte** [comment]
This error: Exception: 'NoneType' object has no attribute 'write'

**Comment by abdnh** [comment]
Strangely, the error doesn't occur when running Anki from the console on Windows. I believe the error happens at [this line](https://github.com/FooSoft/anki-connect/blob/0e467372ebb58e7b2682391fbe0feb3ed02e0aa7/plugin/__init__.py#L199), and ultimately triggered by an attempt by Anki to [print a warning about the usage of a deprecated function](https://github.com/ankitects/anki/blob/8100e81789ed633f862265a47ddbda8aacf3499a/qt/aqt/main.py#L779). This is not specific to AnkiConnect. The error can be actually reproduced using this simple add-on:

```python
import sys
import traceback

traceback.print_stack(file=sys.stdout)

```

**Comment by cjdduarte** [comment]
> Strangely, the error doesn't occur when running Anki from the console on Windows. I believe the error happens at [this line](https://github.com/FooSoft/anki-connect/blob/0e467372ebb58e7b2682391fbe0feb3ed02e0aa7/plugin/__init__.py#L199), and ultimately triggered by an attempt by Anki to [print a warning about the usage of a deprecated function](https://github.com/ankitects/anki/blob/8100e81789ed633f862265a47ddbda8aacf3499a/qt/aqt/main.py#L779). This is not specific to AnkiConnect. The error can be actually reproduced using this simple add-on:
> 
> ```python
> import sys
> import traceback
> 
> traceback.print_stack(file=sys.stdout)
> ```
> 
> UPDATE: this is an issue in Anki. See [ankitects/anki#1786](https://github.com/ankitects/anki/issues/1786)

Tanks. Solved in anki 2.51.rc1
